app/views/setup/rules/_decision_table_fields.html.erb
=> Fix UI Rules Extra facts

.travis.yml, app/controllers/setup/jobs_controller.rb, app/models/dhis2_log.rb, app/models/pyramid.rb, app/services/jobs/last_jobs_service.rb, app/services/jobs/scheduled_jobs_service.rb, app/views/layouts/_header.html.erb, app/views/setup/jobs/_last_job.html.erb, app/views/setup/jobs/_scheduled_job.html.erb, app/views/setup/jobs/index.html.erb, config/routes.rb, spec/controllers/setup/jobs_controller_spec.rb
=> Add views to display enqueued invoice jobs and last produced one

.github/PULL_REQUEST_TEMPLATE.md, Gemfile.lock, app/controllers/setup/invoices_controller.rb, app/helpers/invoices_helper.rb, app/models/invoicing_request.rb, app/services/invoicing/invoice_entity.rb
and adapt project descriptor to report creation
=> Allow empty mock values

Gemfile.lock, app/models/rule_types/zone_rule_type.rb, spec/models/rules_spec.rb
Thanks!
- https://github.com/BLSQ/orbf-rules_engine/pull/15
- https://github.com/BLSQ/orbf-rules_engine/pull/14
- https://github.com/BLSQ/orbf-rules_engine/pull/13
=> Various fixes and allow zone rules cross references

Gemfile.lock, lib/tasks/db.rake
=> rake_db_name_parameterized

app/controllers/setup/activities_controller.rb, app/controllers/setup/projects_controller.rb, app/controllers/setup/states_controller.rb, app/models/activity.rb, app/models/dhis2_name.rb, app/models/formula_mapping.rb, app/models/project.rb, app/models/state.rb, app/services/meta/meta_data_service.rb, app/views/setup/activities/mass_creation.html.erb, app/views/setup/formula_mappings/_formula_mapping_create.html.erb, app/views/setup/setup/_state.html.erb, app/views/setup/setup/_step_dhis2.html.erb, app/views/setup/setup/_step_states.html.erb, app/views/setup/states/_form.html.erb, app/views/setup/states/edit.html.erb, config/routes.rb, db/migrate/20180529094147_add_project_qualifier_to_projects.rb, db/migrate/20180529094514_add_short_name_to_states.rb, db/schema.rb, lib/tasks/db.rake, spec/controllers/setup/activities_controller_spec.rb, spec/controllers/setup/states_controller_spec.rb, spec/factories/projects.rb, spec/models/activity_spec.rb, spec/models/project_spec.rb, spec/models/state_spec.rb
=> Support naming convention

app/models/state.rb, app/views/setup/activities/mass_creation.html.erb, spec/models/state_spec.rb
=> Fix spec for activity code upcase

Gemfile.lock, app/controllers/setup/invoices_controller.rb, app/models/rule_types/activity_rule_type.rb, app/models/rule_types/package_rule_type.rb, spec/models/rules_spec.rb
=> fixes for decision table on a package

app/controllers/setup/metadatas_controller.rb, app/models/formula_mapping.rb, app/models/project.rb, app/services/meta/meta_data_service.rb, app/views/setup/activities/mass_creation.html.erb, app/views/setup/formula_mappings/_formula_mapping_create.html.erb, app/views/setup/metadatas/_metadata.html.erb, app/views/setup/metadatas/_update_data_element.html.erb, app/views/setup/metadatas/index.html.erb, app/views/setup/shared/_dhis2_names.html.erb, app/workers/update_metadata_worker.rb, config/routes.rb, spec/controllers/setup/metadatas_controller_spec.rb, spec/models/formula_mapping_spec.rb, spec/models/state_spec.rb, spec/workers/update_metadata_worker_spec.rb
- align activity.code usage between formula mapping and state mapping
- fix handling of qualifier
- allow to update the data element from metadata screen
=> Fix pattern

app/controllers/setup/autocomplete_controller.rb, app/services/autocomplete/dhis2.rb, app/views/setup/formula_mappings/_formula_mapping.html.erb, spec/controllers/setup/autocomplete_controller_spec.rb
=> Speedup autocomplete

app/assets/stylesheets/application.scss, app/controllers/setup/project_rules_controller.rb, app/controllers/setup/rules_controller.rb, app/models/formula_mapping.rb, app/services/meta/metadata.rb, app/views/setup/invoices/_total_item.html.erb, app/views/setup/metadatas/_metadata.html.erb, app/views/setup/rules/_formula_fields.html.erb, db/migrate/20180615110925_add_short_name_to_formulas.rb, db/schema.rb, spec/controllers/setup/rules_controller_spec.rb
=> Allow formula to have a short name for data element naming convention

Gemfile.lock, app/views/setup/setup/_decision_table.html.erb, app/views/setup/setup/_rule.html.erb
=> Fix payment for zones

Gemfile.lock, app/controllers/setup/projects_controller.rb, app/services/map_project_to_orbf_project.rb, app/workers/project_coc_aoc_reference_worker.rb, db/migrate/20180522124036_add_coc_and_aoc_to_projects.rb, db/schema.rb, spec/services/map_project_to_orbf_project_spec.rb, spec/workers/project_coc_aoc_reference_worker_spec.rb
see https://github.com/BLSQ/orbf-rules_engine/pull/23
- don't fill these for existing project to avoid breaking changes
- fill on new projects
=> Add support for default category combo

Gemfile.lock, app/views/layouts/_header.html.erb
+/- 5 seconds gain on my laptop
=> Perf improvement in rule engine

.rubocop.yml, app/controllers/setup/autocomplete_controller.rb, app/services/autocomplete/dhis2.rb, spec/controllers/setup/autocomplete_controller_spec.rb
=> Autocomplete by id

app/controllers/api/orgunit_history_controller.rb, app/controllers/setup/packages_controller.rb, app/models/periods/year_month.rb, spec/controllers/api/orgunit_history_controller_spec.rb, spec/models/periods/year_month_spec.rb
=> Fix month starting with 0

Gemfile, Gemfile.lock, app/controllers/api/application_controller.rb, app/controllers/api/invoices_controller.rb, app/controllers/api/invoicing_jobs_controller.rb, app/controllers/api/orgunit_history_controller.rb, app/controllers/setup/packages_controller.rb, app/models/invoicing_job.rb, app/models/periods/year_month.rb, app/models/project_anchor.rb, app/serializers/invoicing_job_serializer.rb, app/workers/invoice_for_project_anchor_worker.rb, config/routes.rb, db/migrate/20180810093754_create_invoicing_jobs.rb, db/migrate/20180810100805_add_unique_index_on_invoicing_jobs.rb, db/schema.rb, spec/controllers/api/invoices_controller_spec.rb, spec/controllers/api/invoicing_jobs_controller_spec.rb, spec/controllers/api/orgunit_history_controller_spec.rb, spec/models/concerns/paper_trailed_spec.rb, spec/models/foreign_keys_spec.rb, spec/models/invoicing_job_spec.rb, spec/models/periods/year_month_spec.rb, spec/services/project_factory_spec.rb
WAIT before merging need search
=> Add invoicing jobs

app/workers/discard_invoicing_job_worker.rb, lib/tasks/invoicing_jobs.rake, spec/workers/discard_invoicing_job_worker_spec.rb
=> Feature discard invoicing job

app/models/data_compound.rb, app/models/dhis2_snapshot.rb, app/models/pyramid.rb, app/views/layouts/_header.html.erb, app/workers/dhis2_snapshot_compactor.rb, app/workers/dhis2_snapshot_worker.rb, spec/controllers/setup/autocomplete_controller_spec.rb, spec/services/invoicing/entity_builder_spec.rb, spec/support/webmock_dhis2.rb, spec/workers/dhis2_snapshot_fixture.rb, spec/workers/dhis2_snapshot_worker_spec.rb
=> pagination of DHIS2 resource results

Gemfile.lock
=> upgrade to latest puma

Gemfile.lock, app/helpers/dhis2_helper.rb, app/views/setup/invoices/_activity_item.html.erb, spec/helpers/dhis2_helper_spec.rb
https://github.com/BLSQ/orbf-rules_engine/pull/32
=> Update gem and better cell explanations when indicators or data element with multiple categoryOptionCombos

Gemfile, Gemfile.lock, app/controllers/setup/diagnose_controller.rb, app/controllers/setup/packages_controller.rb, app/models/package.rb, app/services/map_project_to_orbf_project.rb, app/views/setup/diagnose/index.html.erb, app/views/setup/invoices/new_invoice.html.erb, app/views/setup/packages/_form.html.erb, app/views/setup/setup/_package.html.erb, app/views/setup/setup/_step_packages.html.erb, db/migrate/20181003075801_add_group_sets_ext_ids_to_package.rb, db/schema.rb, spec/controllers/setup/packages_controller_spec.rb, spec/factories/packages.rb
Migration
package mapping
invoice descriptor copy button
Thanks!
=> package entity groups match package groupsets

Gemfile.lock
**Previously**
was always the same activity referenced
**With this PR**
now we have different values per activity
=> Upgrade gem to include fix

Gemfile, Gemfile.lock, app/controllers/setup/packages_controller.rb, app/controllers/setup/rules_controller.rb, app/models/package.rb, app/models/package_entity_group.rb, app/models/rule_types.rb, app/services/map_project_to_orbf_project.rb, app/views/setup/diagnose/index.html.erb, app/views/setup/diagnose/show.html.erb, app/views/setup/packages/_form.html.erb, app/views/setup/rules/_form.html.erb, db/migrate/20181105094419_add_kind_to_package_entity_groups.rb, db/schema.rb, spec/controllers/setup/packages_controller_spec.rb, spec/controllers/setup/rules_controller_spec.rb, spec/fixtures/dhis2/organisationUnitGroups-byid-with-target.json, spec/rails_helper.rb, spec/workers/invoice_for_project_anchor_worker_spec.rb
=> Package level aggreg

Gemfile.lock, app/controllers/setup/invoices_controller.rb, app/models/periods/year_month.rb, app/models/periods/year_quarter.rb, app/models/rule_types/activity_rule_type.rb, app/models/rule_types/base_rule_type.rb, app/services/invoicing/invoice_builder.rb, app/services/invoicing/invoice_entity.rb, app/views/setup/invoices/new_invoice.html.erb, spec/models/periods/year_month_spec.rb, spec/models/rules_spec.rb
add support to new engine for
* month_of_quarter
* month_of_year
* quarter_of_year
in activity formulas
sample usage
=> Add support for month_of_quarter in new and old engine

.github/PULL_REQUEST_TEMPLATE.md, app/services/datasets/calculate_desync_datasets.rb, app/services/datasets/to_dhis2_datasets.rb, app/workers/output_dataset_worker.rb, spec/workers/output_dataset_worker_spec.rb
in newer dhis2 version there is an intermediate data_set_elements containing the data_element
in older dhis2 version data elements are directly in data_elements
=> Fix to support dataset on dhis2 2.20

Gemfile.lock, app/controllers/setup/formula_mappings_controller.rb, app/controllers/setup/invoices_controller.rb, app/controllers/setup/rules_controller.rb, app/models/invoicing_request.rb, app/models/package.rb, app/models/rule.rb, app/models/rule_types.rb, app/models/rule_types/zone_activity_rule_type.rb, app/views/setup/invoices/_form.html.erb, app/views/setup/project_rules/_activity_rule.html.erb, app/views/setup/project_rules/_package.html.erb, app/views/setup/rules/_form.html.erb, app/views/setup/setup/_rule.html.erb, app/views/setup/setup/_step_rules.html.erb, script/cibuild, spec/controllers/setup/rules_controller_spec.rb, spec/models/invoicing_request_spec.rb, spec/models/rule_types_spec.rb, spec/models/rules_spec.rb, spec/spec_helper.rb
Add zone activity rules to the application.
Thanks!
=> Zone activity rules

Gemfile.lock, app/assets/javascripts/application.js, app/models/package.rb, app/models/rule_types/activity_rule_type.rb, app/views/layouts/_header.html.erb, app/views/setup/invoices/new.html.erb, app/views/setup/rules/_form.html.erb, app/workers/synchronise_deg_ds_worker.rb, spec/fixtures/dhis2/one_indicator.json, spec/workers/synchronise_deg_ds_worker_spec.rb
Adds support for new features in `orbf-rules_engine`, we now have acces to `<state>_is_null_<anything>_values` and to sliding windows of data, `last_6_months_window_values`.
This exposes those to the webapp. [orbf-rules_engine/40](https://github.com/BLSQ/orbf-rules_engine/pull/40)
Thanks!
=> Sliding windows

app/services/map_project_to_orbf_project.rb, spec/services/map_project_to_orbf_project_spec.rb
Before the fix, the data elements were mapped but not displayed as green cells in the screen
Now they appear green
and the dhis2 values are now generated
=> Fix mapping for zone activity formula

Gemfile.lock
https://github.com/BLSQ/orbf-rules_engine/pull/42
=> Fix indicator eval when negative values

Gemfile, Gemfile.lock, app/services/rules/calculator_factory.rb, app/views/setup/rules/_cheat_sheet_expression.html.erb, spec/lib/rules_engine_spec.rb
The aim of this PR is to be able to use `eval_array` and `array` in the Rails application.
```
eval_array('a', (1,2,3), 'b', (2,3,4), 'b - a')
'a'				=> key 1
'(1,2,3)'	=> array 1
'b'				=> key 2
'(2,3,4)		=> array 2 (needs to be same length as array 1)
'b-a'			=> metaformula
Will loop over the arrays and apply the formula to each index, so
in this example would result in:
(2-1, 3-2,4-3)
(1,1,1)
```
```
array(1,2,3,4,5)
A noop function in this context, mainly added for api parity with
dentaku, so arrays can be explicilty marked as arrays.
ARRAY(1,2,3) => (1,2,3,4,5)
```
This will allow us to use these kind of formulas:
```
"arr" => "array(1,2,-3,4,5)",
"evaled_arr" => "eval_array('a', arr, 'b', arr, 'a - b')",
"result" => "sum(evaled_arr)"
```
And it will successfully calculate that …
=> Upgrade hesabu and rules engine

Gemfile.lock, app/views/setup/rules/_cheat_sheet_expression.html.erb, spec/lib/rules_engine_spec.rb
add support for sqrt
add support for stdevp
PR chain: https://github.com/BLSQ/orbf-rules_engine/pull/47
=> Add stdev and sqrt support

Gemfile.lock
https://github.com/BLSQ/orbf-rules_engine/pull/48
=> Fix dentaku stdevp sqrt signature to prevent validation

app/assets/javascripts/application.js
instead of activating/configuring popover on document ready, wait for the click on it.
=> Improve page rendering performance

Gemfile.lock, doc/capture-and-verify-process.md, lib/data_test/compare.rb, lib/tasks/data_test.rake, yarn.lock
Bumps the rules engine gem and improves the capture/compare documentation.
=> Bump rules engine

app.json
=> Add a bunch of keys with required

app/controllers/setup/rules_controller.rb, app/views/setup/setup/_step_packages.html.erb, app/views/setup/setup/_step_rules.html.erb
* display in a deterministic way the packages
* already give a name to rule to ease the creation of the activity-package-... rules
=> Sort packages and rules by codes

app/controllers/setup/packages_controller.rb, app/models/package.rb, app/services/descriptor/project_descriptor_factory.rb, app/views/setup/packages/_form.html.erb, app/views/setup/project_rules/_package.html.erb, db/migrate/20190619063435_add_description_to_packages.rb, db/schema.rb, spec/controllers/setup/packages_controller_spec.rb, spec/factories/packages.rb, spec/fixtures/scorpio/project_descriptor.json, spec/fixtures/scorpio/project_descriptor_for_zone.json, spec/models/project_spec.rb
add a description to packages
add the same field to the project descriptor
add the field to self-documentation
=> Add description to package

app/controllers/api/workers_controller.rb, config/routes.rb, spec/controllers/api/workers_controller_spec.rb
=> POC to monitor sidekiq

app/workers/invoice_for_project_anchor_worker.rb
Add retry limit to not keep invoice workers for days
=> Add retry limit to not keep invoice workers for days

Gemfile.lock, app/views/setup/rules/_cheat_sheet_expression.html.erb, spec/lib/rules_engine_spec.rb
Add new functions
and associated doc
=> Add floor,ceiling,trunc functions

app/models/project.rb, spec/services/project_factory_spec.rb
=> Copy activity of formula mapping when publishing

app/controllers/api/v2/simulations_controller.rb, spec/controllers/api/v2/simulations_controller_spec.rb
Return the simulations in an order.
=> Simulations should be ordered by updated_at desc

Gemfile.lock
Compañeros PR : https://github.com/BLSQ/orbf-rules_engine/pull/60
=> Reject NaN from a analytics returned values

app/controllers/api/v2/sets_controller.rb, app/serializers/v2/activity_serializer.rb, app/serializers/v2/activity_state_serializer.rb, app/serializers/v2/dhis_value_item_serializer.rb, app/serializers/v2/formula_mapping_serializer.rb, app/serializers/v2/formula_serializer.rb, app/serializers/v2/package_serializer.rb, script/capture-mocked
=> Expose input mappings

lib/tasks/duplicate_jobs.rake
to be scheduled every 10 minutes
=> Rake task to eleminate duplicated workers

app/controllers/setup/autocomplete_controller.rb, app/helpers/invoices_helper.rb, app/views/setup/invoices/_activity_item.html.erb, app/views/setup/invoices/_total_item.html.erb, lib/invoice_entity_to_json.rb, spec/services/map_project_to_orbf_project_spec.rb
=> Fix various issues

Gemfile.lock, app/views/setup/invoices/_activity_item.html.erb, config/environments/development.rb
Some fixes
- dev server wasn't starting anymore to renamed class in the gem.
- make the simulation page work when activity were deleted compared to current projet
=> Dev server was broken due to last renaming

Gemfile.lock
Companion PR of https://github.com/BLSQ/orbf-rules_engine/pull/67
detailed description in other the PR
=> Bump rule_engine : fix %{..._values} expansion

app/serializers/v2/project_anchor_serializer.rb, spec/controllers/api/v2/projects_controller_spec.rb
Simulation propose periods from 2016 up to current year +1
=> Simulation propose periods from 2016 up to current year +1

app/controllers/api/v2/sets_controller.rb, app/models/project.rb, app/serializers/v2/activity_state_serializer.rb, app/serializers/v2/formula_mapping_serializer.rb, app/serializers/v2/formula_serializer.rb, app/serializers/v2/package_serializer.rb, spec/controllers/api/v2/sets_controller_spec.rb
**the formulas were not correctly serialized**
The type in the relationship was topicFormula and the related object was serialized with the type: formula
**not all formulas were returned**
zone, zone_activity,...
=> fix : api v2 : set serialisation of formulas

app/controllers/api/v2/compounds_controller.rb
to follow the same behaviour as in SetsController#show
=> Load formula mapping on compounds

app/controllers/api/v2/sets_controller.rb
=> Missing zone formulas

app/controllers/api/v2/compounds_controller.rb, app/serializers/v2/payment_rule_serializer.rb, spec/controllers/api/v2/compounds_controller_spec.rb
sets were not returned it's not too heavy so added them on index and show
this will allow the hesabu-manager to show the packages next to the formulas.
=> compounds api:  return sets too

app/services/descriptor/project_descriptor_factory.rb, spec/fixtures/scorpio/project_descriptor.json, spec/fixtures/scorpio/project_descriptor_for_zone.json
expose the data element group id added in last PR.
=> Expose data element group id in project descriptor

app/controllers/api/v2/sets_controller.rb, app/serializers/v2/decision_table_serializer.rb, app/serializers/v2/package_serializer.rb
This will enable the hesabu-manager to show things coming from decision tables.
=> Add decision tables to the api

app/controllers/api/v2/projects_controller.rb, app/serializers/v2/project_anchor_serializer.rb, app/serializers/v2/state_serializer.rb
=> Return inputs and their codes

Gemfile.lock
https://github.com/BLSQ/orbf-rules_engine/pull/75
=> Contract view fix

app/models/activity_state.rb, spec/models/activity_spec.rb
external_reference and formula were not that much validated
this PR adds some checks on the format
=> Improve activity state validations

app/controllers/api/v1/application_controller.rb, app/controllers/api/v2/de_cocs_controller.rb, app/controllers/api/v2/formula_mappings_controller.rb, app/models/formula_mapping.rb, app/serializers/v2/de_cocs_serializer.rb, app/serializers/v2/formula_mapping_serializer.rb, app/serializers/v2/package_serializer.rb, config/routes.rb, spec/controllers/api/v2/de_cocs_controller_spec.rb, spec/controllers/api/v2/formula_mappings_controller_spec.rb
=> Add api for formula mappings

Gemfile, Gemfile.lock, app/models/rule_types/activity_rule_type.rb, spec/models/rules_spec.rb
https://github.com/BLSQ/orbf-rules_engine/pull/76
allow to use state_quarterly
=> WIP allow to use state_quarterly

Gemfile.lock
https://github.com/BLSQ/orbf-rules_engine/pull/77
=> DEG are optional

app/controllers/api/v2/topics_controller.rb, spec/controllers/api/v2/topics_controller_spec.rb
not sure that the best way to handle it.
but if the relationships is there synchronize (add or remove the activity from specified packages)
=> Handle sets relationships

.github/workflows/ci.yml, script/cibuild, script/setup
I found this out in d2d, and I made the same errors here. Code climate stopped receiving coverage reports, this makes sure we get them again.
=> Codeclimate was not receiving coverage reports

Gemfile.lock
https://github.com/BLSQ/orbf-rules_engine/pull/82
=> Update orbf rules engine

Gemfile.lock, app/controllers/setup/invoices_controller.rb, app/services/invoicing/entity_signalitic.rb, app/views/setup/invoices/_new_invoice.html.erb, app/views/setup/invoices/new_invoice.html.erb
https://github.com/BLSQ/orbf-rules_engine/pull/83
It's not perfect but the invoice and simulation can be generated
=> Fallback on contract orgunit to avoid pyramid dependency

app/services/groups/list_history.rb
=> Handle missing groupset in past periods

.dockerignore, Dockerfile
=> WIP dockerfile

Gemfile.lock
https://github.com/BLSQ/orbf-rules_engine/pull/84
=> Upgrade orbf-rules engine for ethiopian calendar fix

app/views/setup/invoices/_activity_item.html.erb, app/views/setup/invoices/_total_item.html.erb
=> speed up formula mapping edition from invoice

Gemfile.lock
=> chore: upgrades orbf-rules_engine for golang upgrade

Gemfile.lock, app/models/data_compound.rb, app/views/setup/invoices/_new_invoice.html.erb, lib/invoice_entity_to_json.rb
related PR : https://github.com/BLSQ/orbf-rules_engine/pull/87
=> feat: displays category option combo on simulation for payers

lib/invoice_entity_to_json.rb
=> fixes bug related to projects without contracts in prod

Gemfile, Gemfile.lock, app/controllers/setup/oauth_controller.rb, app/models/program.rb, app/models/project.rb, app/views/setup/setup/_step_dhis2.html.erb, app/views/setup/setup/index.html.erb, config/routes.rb, lib/scorpio.rb, lib/tasks/ui.rake, spec/controllers/setup/oauth_controller_spec.rb
- [ x] Make sure all naming and code will remain understandable in 6 month by someone new to the project or by you.
- [x ] Did I test the right thing?
- [x ] Did I test corner cases, non happy path (defensive testing)?
Thanks!
=> Dhis2 sso - automating set-up via orbf2

app/assets/javascripts/decision_table_fields.js, app/controllers/setup/rules_controller.rb, app/models/decision_table.rb, app/models/rule.rb, app/serializers/v2/decision_table_serializer.rb, app/services/descriptor/project_descriptor_factory.rb, app/views/setup/rules/_decision_table_fields.html.erb, app/views/setup/rules/_decision_tables.html.erb, config/routes.rb, db/migrate/20220404165106_add_name_to_decision_tables.rb, db/migrate/20220404165339_add_comment_to_decision_tables.rb, db/migrate/20220404170152_add_source_url_to_decision_tables.rb, db/schema.rb, spec/controllers/api/v2/projects_controller_spec.rb, spec/fixtures/scorpio/project_descriptor.json, spec/fixtures/scorpio/project_descriptor_for_zone.json
https://user-images.githubusercontent.com/13802104/162415379-22f97b5e-7fa7-4536-b8a5-31762f262ec1.mp4
=> Decision tables downloadable as CSV

app/controllers/oauth/oauth_controller.rb, spec/controllers/oauth/oauth_controller_spec.rb
=> improves error message if no ORBF2 user found with DHIS2 creds

Gemfile.lock
https://github.com/BLSQ/go-hesabu/pull/25
https://github.com/BLSQ/hesabu/pull/17
=> Upgrade hesabu to detect cycles

Gemfile.lock
https://github.com/BLSQ/orbf-rules_engine/pull/88
=> Update orbf rules engine to allow linking between quarterly and monthly packages

app/views/layouts/_header.html.erb
=> Add link to dhis2

app/models/activity.rb, spec/controllers/api/v2/topics_controller_spec.rb, spec/controllers/setup/activities_controller_spec.rb, spec/models/activity_spec.rb
https://user-images.githubusercontent.com/13802104/169483068-8ffedd4c-54a5-445c-bc8d-ed8eb3f6c879.mp4
- [x ] Make sure all naming and code will remain understandable in 6 month by someone new to the project or by you.
- [ x] Did I test the right thing?
Thanks!
=> enforces uniqueness on activity name

app/controllers/api/v2/formula_mappings_controller.rb, app/controllers/setup/formula_mappings_controller.rb, app/workers/create_dhis2_element_for_formula_mapping_worker.rb, app/workers/output_dataset_worker.rb
the spec are not really covering that... but from my local test it's ok
I'll try to find some time to improve that later (famous last word)
=> Add missing data element on output datasets when formula mapping created/modified

app/models/invoicing_request.rb, app/models/project.rb, app/views/layouts/_header.html.erb, app/views/setup/invoices/_form.html.erb, app/views/setup/invoices/new_invoice.html.erb, app/views/setup/setup/_step_dhis2.html.erb, config/initializers/rails_admin.rb, db/migrate/20220530092048_add_invoice_app_path_to_projects.rb, db/schema.rb, lib/tasks/ui.rake, spec/factories/projects.rb, spec/models/project_spec.rb, spec/support/shared_contexts/basic_context.rb
This PR adds an ''Apps" drop-menu in the navigation header to access applications such as the Invoice App for the given project, assignable by the invoice_app_path field on the Project model which is also editable in the Dhis2 setup accordion. This PR also adds a button on the simulation page to navigate to the Invoice App page for the given orgunit's invoices. 
https://user-images.githubusercontent.com/13802104/171194968-0d480830-a571-41de-86c6-8979557a416c.mp4
https://user-images.githubusercontent.com/13802104/171195055-69abe439-85d5-45d2-bb85-12340b9c124e.mp4
=> Navigation enhancements

app/models/invoicing_request.rb, app/views/setup/invoices/_form.html.erb, app/views/setup/invoices/new_invoice.html.erb
=> Direct link to invoice in hesabu manager

app/controllers/api/v2/children_formulas_controller.rb, app/controllers/api/v2/compound_formulas_controller.rb, app/controllers/api/v2/formulas_controller.rb, app/controllers/api/v2/set_formulas_controller.rb, app/controllers/api/v2/topic_formulas_controller.rb, app/controllers/api/v2/zone_formulas_controller.rb, app/controllers/api/v2/zone_topic_formulas_controller.rb, app/serializers/v2/formula_serializer.rb, config/routes.rb, spec/controllers/api/v2/children_formulas_controller_spec.rb, spec/controllers/api/v2/compound_formulas_controller_spec.rb, spec/controllers/api/v2/set_formulas_controller_spec.rb, spec/controllers/api/v2/topic_formulas_controller_spec.rb, spec/controllers/api/v2/zone_formulas_controller_spec.rb, spec/controllers/api/v2/zone_topic_formulas_controller_spec.rb, spec/models/user_spec.rb
https://user-images.githubusercontent.com/13802104/178278856-6767de1d-ccd4-463a-8f12-0ed7897888c5.mp4
Thanks!
=> Makes various set formula types available to hesabu-manager

app/controllers/api/v2/calculations_controller.rb, app/controllers/api/v2/children_formulas_controller.rb, app/controllers/api/v2/compound_formulas_controller.rb, app/controllers/api/v2/set_formulas_controller.rb, app/controllers/api/v2/topic_formulas_controller.rb, app/controllers/api/v2/zone_formulas_controller.rb, app/controllers/api/v2/zone_topic_formulas_controller.rb, app/models/formula.rb, app/models/rule.rb, app/models/rule_types/activity_rule_type.rb, app/models/rule_types/base_rule_type.rb, app/models/rule_types/package_rule_type.rb, app/models/rule_types/payment_rule_type.rb, app/models/rule_types/zone_rule_type.rb, app/serializers/v2/formula_serializer.rb, config/routes.rb, spec/controllers/api/v2/calculations_controller_spec.rb, spec/controllers/api/v2/topic_formulas_controller_spec.rb
adds 
- usedFormulas & usedByFormulas fields
- calculations endpoint for formula testing
- improve usedFormulas & usedByFormulas to lookup upper/lower levels
=> Formulas api

app/controllers/api/v2/inputs_controller.rb, app/controllers/api/v2/set_formulas_controller.rb, app/controllers/api/v2/sets_controller.rb, app/controllers/api/v2/topic_formulas_controller.rb, app/controllers/api/v2/topics_controller.rb, app/controllers/api/v2/users_controller.rb, app/controllers/api/v2/zone_formulas_controller.rb, app/controllers/api/v2/zone_topic_formulas_controller.rb, app/models/rule.rb, app/serializers/v2/package_serializer.rb, app/serializers/v2/user_serializer.rb, config/routes.rb, spec/controllers/api/v2/inputs_controller_spec.rb, spec/controllers/api/v2/sets_controller_spec.rb, spec/controllers/api/v2/users_controller_spec.rb, spec/controllers/setup/packages_controller_spec.rb, spec/support/shared_contexts/basic_context.rb
See title. Related PR for hesabu-manager: https://github.com/BLSQ/hesabu-manager/pull/95
Thanks!
=> Backend API implementation of creation and edition for sets, inputs, topics on hesabu-manager

app/controllers/api/v2/users_controller.rb, app/serializers/v2/user_serializer.rb, spec/controllers/api/v2/users_controller_spec.rb
This PR implements the API to support user management via hesabu manager : https://github.com/BLSQ/hesabu-manager/pull/96
Thanks!
=> Users functionality - API to create, update, list users

app/controllers/api/v2/topic_decision_tables_controller.rb, config/routes.rb, spec/controllers/api/v2/topic_decision_tables_controller_spec.rb
companion : https://github.com/BLSQ/hesabu-manager/pull/97
TODO
=> Allow to create/edit/delete decision tables

app/controllers/api/v2/topic_decision_tables_controller.rb, config/routes.rb, spec/controllers/api/v2/topic_decision_tables_controller_spec.rb
=> implements index endpoint for decision tables

app/controllers/api/v2/compounds_controller.rb, app/serializers/v2/payment_rule_serializer.rb, app/serializers/v2/rule_serializer.rb, config/routes.rb, spec/controllers/api/v2/compounds_controller_spec.rb
API functionality for editing, creating payment rules in hesabu manager https://github.com/BLSQ/hesabu-manager/pull/99
Thanks!
=> Payment rules - API create, update

app/controllers/api/v2/changes_controller.rb, app/serializers/v2/change_serializer.rb, config/routes.rb
=> Changes landing page - api to support hesabu manager

app/controllers/api/v2/input_mappings_controller.rb, app/models/activity_state.rb, app/serializers/v2/formula_serializer.rb, config/routes.rb, spec/controllers/api/v2/input_mappings_controller_spec.rb
This PR would allow for the creation and edition of input mappings in hesabu manager.
Thanks!
=> Input mappings - create, update

app/controllers/setup/projects_controller.rb, app/models/dhis2_log.rb, app/models/dhis2_snapshot.rb, app/models/dhis2_snapshot_change.rb, app/models/project.rb, app/models/project_anchor.rb, app/services/invoicing/invoice_entity.rb, app/views/setup/setup/_step_dhis2.html.erb, db/migrate/20221011074011_add_dhis2_logs_enabled_to_project.rb, db/schema.rb, lib/tasks/daily.rake, lib/tasks/ui.rake, spec/factories/dhis2_snapshots.rb, spec/factories/projects.rb, spec/models/dhis2_snapshot_spec.rb, spec/models/project_spec.rb
Add 2 boolean flags on project (I prefer that than flipper, since they are long lasting option)
- enabled : to stop triggering deployment and snapshot on dead projects/dhis2
- enabled_dhis2_logs : to stop logging posted values and its status in db
=> Add enabled and enabled_dhis2_logs to project config

app/views/setup/setup/_rule.html.erb
=> Add some null safe check

app/workers/dhis2_snapshot_worker.rb, app/workers/invoice_for_project_anchor_worker.rb
=> ttl for worker

app/workers/invoice_for_project_anchor_worker.rb
=> Add sleep at startup and fix fork mode

Gemfile.lock, app/controllers/api/v1/invoicing_jobs_controller.rb, app/controllers/api/v2/simulations_controller.rb, app/controllers/setup/invoices_controller.rb, app/models/invoicing_request.rb, app/models/package.rb, app/models/payment_rule.rb, app/models/periods.rb, app/models/project.rb, app/models/rule_types/activity_rule_type.rb, app/serializers/v2/project_anchor_serializer.rb, app/services/datasets/to_dhis2_datasets.rb, app/services/invoicing/invoice_entity.rb, app/services/invoicing/map_to_invoices.rb, app/services/rules/solver.rb, app/workers/invoice_for_project_anchor_worker.rb, app/workers/invoice_simulation_worker.rb, lib/invoice_entity_to_json.rb, spec/controllers/api/v2/compounds_controller_spec.rb, spec/models/periods/periods_spec.rb, spec/models/rules_spec.rb
=> Ethiopian calendar v2

app/controllers/api/v2/descriptors_controller.rb, app/controllers/api/v2/sets_controller.rb, app/serializers/v2/package_serializer.rb, config/routes.rb
=> Add deg to api and descriptor endpoint

Gemfile.lock, app/services/analytics/locations/level_scope.rb
=> ethiopian calendar v2 : parent quarterly_nov
