BLSQ/orbf2

Gemfile.lock
3-4 seconds improvement on my laptop
mainly, for all engine value object, having initializer and attr_reader hand written instead of letting ValueObject do it via "send and instance_variable_get"
https://github.com/BLSQ/orbf-rules_engine/blob/master/lib/orbf/rules_engine/value_object.rb#L11
https://github.com/BLSQ/orbf-rules_engine/blob/master/lib/orbf/rules_engine/data/variable.rb#L128
before 15 seconds
after 10.5 seconds
=> Upgrade hesabu and orbf-rules_engine to remove gc pressure

app.json, config/initializers/sidekiq.rb, spec/config/lint_data_files_spec.rb
Adding an app.json for two reasons:
- Ability to (technically) add a deploy button to the readme
- Allow for Review apps
The second one is the feature here. If we setup a pipeline on Heroku
this means that a PR can be deployed to a functioning application
Heroku with the press of a button.
It uses the app.json to setup a new app, which has the required env
variables and a redis and postgres set up and running, so it basically
removes any friction to set up an app to test out the PR.
https://devcenter.heroku.com/articles/heroku-button
https://devcenter.heroku.com/articles/app-json-schema#formation
=> Make Heroku deploys easier

.travis.yml, README.md, app.json, app/controllers/setup/seeds_controller.rb, app/services/project_factory.rb, config/application.rb, config/routes.rb, db/seeds.rb, lib/scorpio.rb, script/bootstrap, script/cibuild, script/console, script/server, script/setup, script/test, script/update, spec/lib/scorpio_spec.rb
This makes getting up and running, easier. It does this in a number of ways
These are modeled after https://github.com/github/scripts-to-rule-them-all, they provide a standard way across repos to:
- `script/bootstrap` (resolve dependencies)
- `script/setup` (setup entire project)
- `script/console` (get a console)
- `script/cibuild` (what ci calls)
- `script/test` (runs test)
- `script/update` (Updates your env to latest version)
So now a new user only needs to do `script/setup` and he should have everything needed to start working on orbf2
Review apps now inherit the `DEFAULT_USER_EMAIL`, `ADMIN_PASSWORD` and `DEFAULT_USER_PASSWORD` from the staging application on Heroku. By default they're also set, but by inheriting them from the staging environment we limit access to the review apps …
=> Improve initial setup experience

Gemfile.lock, app/assets/javascripts/activities_controller.js, app/controllers/setup/activities_controller.rb, app/models/activity_state.rb, app/services/activities/activity_state_attributes.rb, app/services/activities/add_to_activity_states.rb, app/services/map_project_to_orbf_project.rb, app/views/setup/activities/_constant.html.erb, app/views/setup/activities/_form.html.erb, app/workers/synchronise_deg_ds_worker.rb, spec/controllers/setup/activities_controller_spec.rb, spec/models/activity_spec.rb
allow to add data elements with category options as activity state.
for the rules engine, they will behave like indicators
the synchronisation of data element/data element group
I know that some part of the ui is not 100% ok (eg metadata, simulation page )
but we should probably start configuring the SIGL project beginning next week.
=> add category option combo support

.gitignore, Gemfile, Gemfile.lock, app/models/invoicing_request.rb, app/services/invoicing/invoice_entity.rb, doc/capture-and-verify-process.md, lib/data_test.rb, lib/data_test/capture.rb, lib/data_test/compare.rb, lib/data_test/fetcher.rb, lib/data_test/file_helpers.rb, lib/data_test/subject.rb, lib/data_test/uploader.rb, lib/data_test/verifier.rb, lib/tasks/data_test.rake, lib/tasks/spec.rake, script/bootstrap, script/cibuild, script/setup, spec/lib/data_test_spec.rb, spec/spec_helper.rb
We want an automated, reliable check to see if adjustments made to:
- hesabu
- hesabu-go
- orbf-rules_engine
- orbf2
Have an impact on previously made calculations.
In order to do this we've identified several projects and org units that we want to check by using production data and comparing the results to a newer version.
See `lib/data_test.rb`, it's a module which has helpers for the various parts:
- `lib/data_test/capture.rb` -> Capturing the artefacts
- `lib/data_test/verifier.rb` -> Verifying the results
- `lib/data_test/uploader.rb` -> Upload to S3
- `lib/data_test/fetcher.rb` -> Fetchhing from S3
Normally we don't interact with those classes, since the verifier gets run by the spec suite (`rake spec:data_test`) and the capture and upload is also available as a single rake task …
=> Capture and verify process

.rubocop.yml, Gemfile, Gemfile.lock, app/models/project_anchor.rb, app/models/user.rb, app/services/invoicing/invoice_entity.rb, config/application.rb, config/initializers/feature_flipper.rb, config/routes.rb, db/migrate/20190214095526_create_flipper_tables.rb, db/schema.rb, lib/data_test.rb, lib/parallel_dhis2.rb, spec/lib/data_test_spec.rb, spec/lib/parallel_dhis2_spec.rb, spec/models/concerns/paper_trailed_spec.rb, spec/services/invoice_entity_spec.rb, spec/services/project_factory_spec.rb
While publishing a rather large invoice, I found out that most of the time was spent in publishing to DHIS2.
When sending 11040 values to dhis2:
- Single request:    43 seconds (43093.83299993351)
- Parallel requests:  8 seconds (8223.681999836117)
Sending 3046 values had these results:
- Single request:  12 seconds
- Parallel rquests: 6 seconds
So big wins all around. I've also checked this on the DHIS2 side to confirm that the data is arriving.
``` sql      
select datavalue.lastupdated from datavalue 
join organisationunit ON organisationunit.organisationunitid = datavalue.sourceid 
join dataelement ON dataelement.dataelementid = datavalue.dataelementid 
where 
dataelement.uid = 'WQbeZuIvhzS' and organisationunit.uid = 'XJkQtdGRO5Q';
```
And it was updating the lastupdated, it was also …
=> Parallel http requests

lib/data_test.rb, lib/data_test/fetcher.rb, lib/data_test/uploader.rb
The rake task requires it so it gets loaded, since datatest is
requiring `aws-sdk-s3` for fetching and uploading, and this gem is
only installed in development/test, on production it would break.
Heroku runs into this when trying to detect rake tasks:
Could not detect rake tasks
!     ensure you can run `$ bundle exec rake -P` against your app
!     and using the production group of your Gemfile.
!     rake aborted!
!     LoadError: cannot load such file -- aws-sdk-s3
This makes it loadable but fetching and uploading won't be
available (and they shouldn't be!)
Thanks!
=> DataTest should be loadable in production

app/models/project_anchor.rb, app/services/invoicing/invoice_entity.rb
The pyramid is now only constructed once (in the orbf rules engine
gem), instead of doint it twice.
~This change needs the pj/performance-tweaks branch of orb rules engine to be merged first.~
Changed was merged, and this PR updates orbf-rules_engine
Thanks!
=> Avoid double construction of pyramid

app/models/rule_types/activity_rule_type.rb, app/services/rules/solver.rb, app/services/rules/values_mocker.rb, spec/models/formula_spec.rb, spec/services/rules/solver_spec.rb
this kind of formula was not editable because the mocked values used to verify the coherence between formulas were not in the "expected" length.
```
sum(
eval_array(
'last_months_values_null_e',  ARRAY(%{method_patient_active_is_null_last_3_months_window_values}),
'earliest_month_check',     ARRAY(1,0,0),
'if( earliest_month_check == 1 AND last_months_values_null_e == 0, 1 , 0)'
)
)
```
ending with error message
```
Formulas EVAL_ARRAY() requires 'last_months_nulls' and 'earliest_month_check' in (if( earliest_month_check == 1 AND last_months_nulls == 0, 1 , 0)) to have same size of values 
```
because the formula "tested" was 
```
sum(
eval_array(
'last_months_nulls',  ARRAY(1 , 2),
'earliest_month_check',     ARRAY(1,0,0),
'if( earliest_month_check == 1 AND last_months_nulls == 0, 1 , …
```
=> Add values mocking for current_quarter and time window _values

app/controllers/setup/invoices_controller.rb, app/views/setup/invoices/_form.html.erb, app/views/setup/invoices/new_invoice.html.erb, spec/controllers/setup/invoices_controller_spec.rb
Some of our simulations loaded so many org units, which loaded so many tables that the view rendering took to long and ran over the Heroku request. To solve this we're doing two things:
- Make the view rendering async (coming to another PR)
- Allow user to select which org units to simulate (this PR)
- Copying URL, will include the selected org units
- If left blank all org units will be returned
- Views have been slightly tweaked to make it clear to user.
The location of the `OrgUnitLimiter` source. On the one hand, I like that it's only in the Controller. On
the other hand I'm not that much a fan of stowing it in the controller.
It's somewhere between Presenter, ViewModel and Service
=> Allow a user to select org units before simulation

Gemfile, Gemfile.lock
I keep readding it while developing only to remove it when committing, so now is as good a time as any to make it more permanent.
Why?
Glad you asked, the main reasons are:
- Source code highlighting
- `cd` into objects, `ls` in objects to view their methods
- `$ some_method` shows the source of the method
- `. some_shell_command` will run the shell command
- `e Thing#thing` will open an editor with the Thing#Thing opened, I use this a lot to view Rails internals.
It has a lot of other features, but those I use less.
=> Add Pry as a dev dependency

lib/parallel_dhis2.rb, spec/lib/parallel_dhis2_spec.rb
Ran into this in production, if the password contains some characters that are not allowed in the URL (so they get HTML escaped), `ParallelDhis2` would simply use the escaped version (which was not the correct password).
Thanks!
=> Handle passwords with HTML escaped chars

Gemfile, Gemfile.lock, app/controllers/setup/packages_controller.rb, app/models/package.rb, app/services/map_project_to_orbf_project.rb, app/views/setup/packages/_form.html.erb, db/migrate/20190314135553_add_include_main_orgunit_to_packages.rb, db/schema.rb, spec/controllers/setup/packages_controller_spec.rb, spec/factories/packages.rb, spec/lib/data_test_spec.rb, spec/services/map_project_to_orbf_project_spec.rb
requires https://github.com/BLSQ/orbf-rules_engine/pull/46
In burundi scheme, we'd like to allow zone packages with "groupset" to allow adding the main orgunit as a target too. To avoid breaking existing behaviour (think Liberia ) a new option has been added to include_main_orgunit or not.
=> Allow to include main orgunit as target in zone package

app/workers/invoice_for_project_anchor_worker.rb, spec/workers/invoice_for_project_anchor_worker_spec.rb
Very small PR to expose the maximum number of concurrent invoices for a project anchor.
Currently they're limited to 3 per project_anchor, by exposing it to an ENV variable:
`SDKQ_MAX_CONCURRENT_INVOICE`
We can tweak this at runtime for some additional processing power.
`heroku config:set SDKQ_MAX_CONCURRENT_INVOICE=4 -a <app-name>`
If none is set it will default to 3 (which is the current amount).
=> Allow tweaking of the number of concurrent invoices at runtime

Gemfile.lock, app/services/analytics/locations/level_scope.rb, spec/models/rules_spec.rb
this PR bundles the rule engine changes to support ..._level_X_quarterly : https://github.com/BLSQ/orbf-rules_engine/pull/49
this add "auto completetion" in variable edition 
the simulation with the modified formula shows the quaterly value of the parent
TODO : verify legacy engine is not impacted
=> Add support level x quarterly

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/unlocks/new.html.erb
From the Devise Changelog [0]
deprecations:
- The second argument of DatabaseAuthenticatable's #update_with_password and #update_without_password is deprecated and will be removed in the next major version. It was added to support a feature deprecated in Rails 4, so you can safely remove it from your code. (by @ihatov08)
- The DeviseHelper.devise_error_messages! is deprecated and will be removed in the next major version. Use the devise/shared/error_messages partial instead. (by @mracos)
So I've removed the `devise_error_messages!` from our views and
replaced them with the partials. I tried sign up and forgot views. The
others I eyeballed the code.
[0] https://github.com/plataformatec/devise/blob/2e5b5fcd705b06c518ab0156b96badb91c4cb6ea/CHANGELOG.md
=> Devise 4.5.0 -> 4.6.2

app/workers/invoice_simulation_worker.rb, spec/workers/invoice_for_project_anchor_worker_spec.rb, spec/workers/invoice_simulation_worker_spec.rb, spec/workers/project_fixture.rb
- adding a spec on top of your branch
- mocking some s3 components as tests are using file/disk storage
fix-issues-with-async-deployment :
-   4385 / 5055 LOC (86.75%) covered.
add-spec-for-simulation : 
-   4472 / 5053 LOC (88.5%) covered.
tried to expect the simulation values compared to a stored one but looks like the output is not so deterministic to compare nested hash vs nested hash.
=> Add spec for simulation worker

Gemfile, app/controllers/setup/invoices_controller.rb, app/javascript/packs/components/loader.jsx, app/models/invoicing_job.rb, app/models/invoicing_simulation_job.rb, app/models/project_anchor.rb, app/serializers/invoicing_job_serializer.rb, app/workers/invoice_simulation_worker.rb, config/application.rb, db/migrate/20190424081026_change_state_default_to_enqueued.rb, db/schema.rb, lib/invoice_entity_to_json.rb, script/bootstrap, spec/controllers/api/invoicing_jobs_controller_spec.rb, spec/factories/invoicing_jobs.rb, spec/factories/project_anchors.rb, spec/models/invoicing_job_spec.rb, spec/models/project_anchor_spec.rb, spec/workers/invoice_for_project_anchor_worker_spec.rb, spec/workers/invoice_simulation_worker_spec.rb, spec/workers/project_fixture.rb
I deployed the async version on staging and during testing of that I ran into these issues:
- Projects sometimes didn't have a token set
- Jobs without a state were considered 'alive' (which was wrong)
- Error handling was not that great (now showing actual errors)
- Errors during simulation now bubble up to the user
- ActiveJob used its own async instead of sidekiq
- Cleaned up bootstrap script to include yarn
=> Fix issues we had during async

app/controllers/setup/activities_controller.rb, app/controllers/setup/project_rules_controller.rb, app/models/decision_table.rb, app/models/package.rb, app/models/package_state.rb, app/models/project.rb, app/models/rule_types/activity_rule_type.rb, app/models/rule_types/base_rule_type.rb, app/models/rule_types/multi_entity_rule_type.rb, app/models/rule_types/package_rule_type.rb, app/models/rule_types/zone_activity_rule_type.rb, app/models/state.rb, app/services/analytics/locations/level_scope.rb, app/services/analytics/multi_entities_calculator.rb, app/services/analytics/timeframe/previous_year.rb, app/services/project_factory.rb, app/views/setup/activities/_constant.html.erb, app/views/setup/packages/_form.html.erb, app/views/setup/project_rules/_rule.html.erb, app/views/setup/setup/_readonly.html.erb, app/views/setup/setup/index.html.erb, db/migrate/20190416082904_remove_level_on_states.rb, db/schema.rb, spec/controllers/setup/activities_controller_spec.rb, spec/controllers/setup/project_rules_controller_spec.rb, spec/models/concerns/paper_trailed_spec.rb, spec/models/state_spec.rb, spec/services/project_factory_spec.rb
- remove level column on state
- avoid package.states usage in validations (empty when publishing/cloning)
- avoid package.activities usage in validations (empty when publishing/cloning)
- added papertrail on state
- allow to display documentation on published and draft projects.
- fix deep_clone config to actually clone [everything](https://github.com/moiristo/deep_cloneable#the-dictionary-object-reusage).
TODO
- add spec for publishing : partially done.
the spec `./spec/services/project_factory_spec.rb` is already better but was not failing on the activity_package as on production project. I don't really found (I think states and activities are not reused) and so might not trigger the same issues but project deep_clone config was clearly not good
This spec on dev branch the …
=> fix versioning and drop state levels

Procfile, app/controllers/setup/invoices_controller.rb, app/javascript/packs/components/invoice/explanation_row.jsx, app/javascript/packs/components/invoice/explanation_steps.jsx, app/javascript/packs/components/invoice/solution.jsx, app/javascript/packs/components/invoice/table.jsx, app/javascript/packs/components/invoice/table_row.jsx, app/javascript/packs/components/invoice/total_items.jsx, app/models/invoicing_simulation_job.rb, app/workers/invoice_simulation_worker.rb, lib/invoice_entity_to_json.rb, spec/workers/invoice_simulation_worker_spec.rb
fix the first_or_create by providing an adequate scope
you can then safely start bundle exec sidekiq -q dhis2-safe
on your laptop without the risk of running write workers (data element, dataset creation/modification)
=> Fix various issues with async simulation

app/controllers/setup/invoices_controller.rb, app/models/invoicing_job.rb, app/models/invoicing_request.rb, app/views/setup/invoices/_form.html.erb, app/workers/invoice_simulation_worker.rb, config/initializers/rails_admin.rb, spec/models/invoicing_job_spec.rb, spec/workers/invoice_simulation_worker_spec.rb
- Bring back mocked values
- Allow user to use draft version
- Use paper trail to determine if simulation needs to reloaded
Looks like ![this](https://pile.pjaspers.com/Screen-Shot-2019-05-15-13-56-27.55-jpIDm4.png)
=> Bring async options up to par with normal simulation

app/views/setup/packages/_form.html.erb
When a lot different entities and activities, it's hard find the activities back in the list.
Being able to filter on the code might help.
=> Show the code in activity selection for package creation

Gemfile, Gemfile.lock, app/controllers/setup/activities_controller.rb, app/models/activity_state.rb, app/models/invoicing_request.rb, app/services/map_project_to_orbf_project.rb, app/views/setup/activities/_activity_state.html.erb, app/views/setup/activities/_form.html.erb, app/views/setup/invoices/_activity_item.html.erb, app/views/setup/setup/_activity.html.erb, app/workers/synchronise_deg_ds_worker.rb, db/migrate/20190703055831_add_origin_to_activity_states.rb, db/schema.rb, spec/workers/invoice_for_project_anchor_worker_spec.rb, spec/workers/invoice_simulation_worker_spec.rb
Not all indicators are "easy to compute" from aggregate data elements.
For example indicators referencing : reporting rates,  constants, program indicators, org unit count.
This clearly open the door to 
- flexibility : 
- eg get average statisfaction score from a tracker program and store it in an aggregate/frozen data element
- troubles : 
- cycle between data element filled by orbf2 and indicators 
- extra delays to produce invoices as need a clean analytics run to get latest "satisfaction score"
Allow to assign a "origin" of the data in the activity state mapping
and use /api/analytics to calculate invoices
values that looks like the one in pivot
https://github.com/BLSQ/orbf-rules_engine/pull/54
=> Add origin to activity state

.travis.yml, app/models/rule_types/activity_rule_type.rb, spec/models/rules_spec.rb
orbf-rules-engine already can handle these, we were just not exposing
them to the world.
This means that you can now access the last 4 quarters with:
%{claimed_is_null_last_1_quarters_exclusive_window_values}
%{claimed_is_null_last_1_quarters_window_values}
%{claimed_is_null_last_2_quarters_exclusive_window_values}
%{claimed_is_null_last_2_quarters_window_values}
%{claimed_is_null_last_3_quarters_exclusive_window_values}
%{claimed_is_null_last_3_quarters_window_values}
%{claimed_is_null_last_4_quarters_exclusive_window_values}
%{claimed_is_null_last_4_quarters_window_values}
%{claimed_last_1_quarters_exclusive_window_values}
%{claimed_last_1_quarters_window_values}
%{claimed_last_2_quarters_exclusive_window_values}
%{claimed_last_2_quarters_window_values} …
=> Expose quarterly values to montly packages as well

.travis.yml, Gemfile.lock
Updating to being bundled by `bundler` version 2.
This fixes the builds on Travis being broken (or having to hardcode an old version of bundler in the travis.yml)
This also brings in an update to the orbf rules engine, [this commit](https://github.com/BLSQ/orbf-rules_engine/commit/72b5004a046e5bd4427f863c1537db4133b0b516) which looks to add extra info on some error cases, so I'd say safe to merge it in here as well.
=> Update to bundler 2

README.md, app/views/layouts/private.html.erb
Only if ENV is present, so in order for this to land in production we'll need to set the ENV there.
=> Conditionally enable Logrocket

app/javascript/packs/components/invoice/invoice_header.jsx, app/javascript/packs/components/invoice/table.jsx, app/javascript/packs/components/loader.jsx, package.json, yarn.lock
I ran:
npm install -g npm-check-updates
npm-check-updates
Which will print the changes available:
@babel/preset-react       ^7.0.0  →    ^7.6.3
@material-ui/core         ^3.9.2  →    ^4.5.0
@rails/webpacker           4.0.1  →     4.0.7
babel-eslint             ^10.0.1  →   ^10.0.3
eslint-config-prettier    ^4.1.0  →    ^6.4.0
eslint-plugin-import     ^2.16.0  →   ^2.18.2
lodash                  ^4.17.13  →  ^4.17.15
react                    ^16.8.3  →  ^16.10.2
react-dom                ^16.8.3  →  ^16.10.2
webpack-cli               ^3.2.3  →    ^3.3.9
eslint-plugin-prettier    ^3.0.1  →    ^3.1.1
eslint-plugin-react      ^7.12.4  →   ^7.16.0
prettier-eslint           ^8.8.2  →    ^9.0.0
prettier-eslint-cli       ^4.7.1  →    ^5.0.0
webpack-dev-server         3.2.1  →     3.8.2
Then …
=> Fix js dependencies

config/application.rb, config/routes.rb, lib/can_access_developer_tools_constraint.rb, lib/scorpio.rb, spec/lib/scorpio_spec.rb, spec/rails_helper.rb, spec/requests/developer_constraints_spec.rb
This allows certain users to be whitelisted as developers
ENV["DEV_USER_IDS"] = "1,2,3"
And have access to the developer tools without having to remember the
admin password.
If you only know the ADMIN_PASSWORD, a curl request with basic
authentication will also still work. But the browser won't prompt you anymore.
Thanks!
=> Developer constraint

.travis.yml, app/views/setup/setup/_step_publish.html.erb
remove the changelog between "versions" of projects 
as it triggers multiple project loading and select n+1
=> Perf : disable the changelog display on published projects

lib/tasks/db.rake
dhis2_snapshots is huge and db pulling is hard without blocking production
=> Exclude dhis2_snapshots from db:pull to speed up the process

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/controllers/private_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/_header.html.erb, app/views/layouts/private.html.erb, config/application.rb, config/routes.rb, lib/can_access_developer_tools_constraint.rb, lib/scorpio.rb, spec/lib/scorpio_spec.rb, spec/rails_helper.rb, spec/requests/developer_constraints_spec.rb
Adds a user switching mechanism when:
- In development environment
- In staging environment
- Your user id is in DEV_USER_IDS
It will look like this when impersonating: ![](https://pile.pjaspers.com/Screen-Shot-2019-10-09-12-18-34.14-fjy1DL.png)
The user switcher is just a list in a <details> so looks like this:
Thanks!
=> Add user switcher for devs

app/models/project.rb, db/migrate/20191224083227_add_publish_end_date_to_projects.rb, db/schema.rb, spec/models/project_spec.rb
* add publish_end_date on project
* adapt query look up by dates
this the behavior with a publish_end date
https://github.com/BLSQ/orbf2/pull/162/files#diff-fb312d8dcf15fea2e04d19523d09ff27R87
```
2012Q1	 => 	7	2012-01-01 00:00:00 UTC	2012-12-31 23:59:59 UTC
2012Q2	 => 	7	2012-01-01 00:00:00 UTC	2012-12-31 23:59:59 UTC
2012Q3	 => 	7	2012-01-01 00:00:00 UTC	2012-12-31 23:59:59 UTC
2012Q4	 => 	7	2012-01-01 00:00:00 UTC	2012-12-31 23:59:59 UTC
2013Q1	 => 	8	2013-01-01 00:00:00 UTC	2014-12-31 23:59:59 UTC
2013Q2	 => 	8	2013-01-01 00:00:00 UTC	2014-12-31 23:59:59 UTC
2014Q3	 => 	8	2013-01-01 00:00:00 UTC	2014-12-31 23:59:59 UTC
2014Q4	 => 	8	2013-01-01 00:00:00 UTC	2014-12-31 23:59:59 UTC
2015Q1   => nil
```
=> Adapt project look up for a date with publish end date

Gemfile.lock, app/models/project.rb, app/services/invoicing/map_to_invoices.rb, app/services/map_project_to_orbf_project.rb, app/workers/dhis2_snapshot_worker.rb, db/migrate/20200115140940_add_calendar_name_to_project.rb, db/schema.rb, lib/data_test/verifier.rb, lib/tasks/db.rake, spec/factories/projects.rb, spec/models/project_spec.rb
https://github.com/BLSQ/orbf-rules_engine/pull/58
This add support for Ethiopian calendar. 
- add a calendar_name on project the default stays gregorian
- the calendar will be passed to the orbf-rules_engine to get the "quarter's month" rights
- the calendar is also used to store the snapshot (eg if snapshoted today will be stored with 2012/05)
As it's specific and allowing people to change it is more "trouble", I opted to just update the calendar name.
Ideally we should get rid of [Periods](https://github.com/BLSQ/orbf2/tree/dev/app/models/periods) but it's still in use in a few places and don't really have time to do it now. Will make an issue about it.
=> add ethiopian calendar support

script/capture-mocked
(Needs to be merged after expose sets)
This is basically a single commit: 06a70e2 (after the expose sets PR has been merged) which will allow us to do this:
This script can be used to capture data to store in the
`hesabu-manager`[0]
The idea is that you run a server locally and then run this script,
so that the JSON gets stored and managed ever so slightly so that we
don't need to make external requests to S3.
[0] https://github.com/BLSQ/hesabu-manager/tree/develop/mock-server/data
=> Capture mocked data from project

app/controllers/setup/invoices_controller.rb
Change the current year/quarter default for the simulation page.
We should probably do something similar in the hesabu manager.
Where should we put it ? on the /api/projects ?
=> Default to current year/quarter based on calendar and not iso today

app/workers/invoice_for_project_anchor_worker.rb, spec/workers/invoice_for_project_anchor_worker_spec.rb
The downside is that we won't notice them anymore, the upside is that the queue stays clean (for now)
I'll work on something to help us keep noticing them, but it might be a good idea to deploy this to avoid the queue congestion.
=> Don't retry on failed equations

.travis.yml, Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/setup/autocomplete_controller.rb, app/controllers/setup/invoices_controller.rb, app/controllers/setup/main_entity_groups_controller.rb, app/models/entity_group.rb, app/models/project.rb, app/services/invoicing/entity_signalitic.rb, app/services/map_project_to_orbf_project.rb, app/views/setup/setup/_step_entities.html.erb, app/workers/synchronise_groups_worker.rb, config/routes.rb, db/migrate/20200608065708_add_contract_settings_to_entity_groups.rb, db/migrate/20200624112533_add_group_synchronisation_to_entity_groups.rb, db/schema.rb, lib/invoice_entity_to_json.rb, lib/tasks/group_sync.rake
*Contracts settings are now stored on EntityGroup*
to avoid collision with program_id as foreign key to the hesabu/program, renamed them with _reference
I have failing tests... need to investigate why
TODO : 
WHEN deploying:
=> Add support for contracts

Gemfile.lock
This brings in https://github.com/BLSQ/orbf-rules_engine/pull/66
Which makes our analytics fetching more resilient when it has to handle lots of periods (it makes multiple calls, which doesn't bring DHIS down)
=> Bump orbf-rules_engine

lib/parallel_dhis2.rb, spec/lib/parallel_dhis2_spec.rb
The parallel publisher would interpret the user as "Name+Something" instead of "Name Something" so DHIS would return 401's.
=> Fix: DHIS users with spaces could not parallel publish

app/workers/invoice_for_project_anchor_worker.rb
So instead of sharing the lock across dyno's this will mean that each
dyno can run SDKQ_MAX_CONCURRENT_INVOICE invoices per project anchor
on each dyno.
=> Add throttle per worker

Gemfile.lock, app/models/rule_types/activity_rule_type.rb, app/models/rule_types/base_rule_type.rb, app/views/setup/rules/_cheat_sheet_expression.html.erb, spec/lib/rules_engine_spec.rb, spec/models/rules_spec.rb
companion PRs
- https://github.com/BLSQ/go-hesabu/pull/20
- https://github.com/BLSQ/hesabu/pull/13
- https://github.com/BLSQ/orbf-rules_engine/pull/69
**add support to calculate the number of days of a month**
you have now 
- access to the `year` of the invoice as period fact and 
- a function `cal_days_in_month(year, month_of_year)`
**limitations:** won't work on Ethiopian calendar...
=> Add cal_days_in_month and year as a period fact

lib/tasks/ui.rake
Setup the datastore config for hesabu to be shared between [invoiceapp](https://github.com/BLSQ/blsq-report-components/blob/add-contracts-support/src/components/invoices/InvoicePlugin.js#L16) and the [hesabu manager](https://github.com/BLSQ/hesabu-manager/)
Individually for a given project anchor
```
rake ui:setup[98]
```
or for all project anchors
```
rake ui:setup_all
```
=> Allow to setup hesabu token in dhis2 datastore

lib/parallel_dhis2.rb, script/setup, spec/lib/parallel_dhis2_spec.rb
I don't know why, but sometimes the error popups:
https://sentry.io/organizations/bluesquareorg/issues/1850775543/?project=213257&query=is%3Aunresolved
This will make it so that it doesn't error, and maybe shows what is the root cause of the error.
It does have responses (otherwise we would get an empty hash back in the hash) so it needs to be having responses returned that don't carry the `data_set_complete`, so maybe it's a one-off DHIS thing. It doesn't happen always, but on a set of 500-ish invoices, it's bound to happen on one of them.
=> Fix responses without dataset complete

app/services/rules/values_mocker.rb, spec/services/rules/solver_spec.rb
The regex only took the last one, so it supplied an incorrect number of values for the array, thus creating an error.
=> Also support last_xx_months_values

app/controllers/api/v2/projects_controller.rb, app/serializers/v2/package_serializer.rb, app/serializers/v2/project_anchor_serializer.rb, spec/controllers/api/v2/projects_controller_spec.rb
To ease investigations/lookups, I've added a way to load the project.
According to json api spec, `include` is supposed to be a list of relationships, I've introduced a param called `profile`.
That list of relationship is really really long and didn't wanted to have the client to known about all the ramifications
I prefered to use `?profile=full`
example usage from taskr
```js
const api = await dhis2.api();
const hesabu = await api.get("dataStore/hesabu/hesabu");
const projectJson = await fetch(hesabu.url + "/api/project?profile=full", {
credentials: "omit",
headers: {
"X-Token": hesabu.token,
Accept: "application/vnd.api+json;version=2"
}
}).then(r => r.json());
const project = JSONApi.deserialize(projectJson);
JSON.stringify(project, (key, value) => {
return …
```
=> Jsonapi fetch project fully

lib/invoice_entity_to_json.rb
the key was added in the previous PR but wasn't in the json
=> Simulation : add key for total item in the json

app/controllers/api/v2/base_controller.rb, app/controllers/api/v2/input_mappings_controller.rb, app/controllers/api/v2/topics_controller.rb, config/routes.rb, spec/controllers/api/v2/input_mappings_controller_spec.rb, spec/controllers/api/v2/topics_controller_spec.rb, spec/factories/activities.rb, spec/factories/states.rb
a first create/update api for topic and input mappings (as a nested resource)
I'll merge that to be able to automate my hesabu projet from taskr.
I'm ready to break the api in case you have other preferences.
It's a bit unclear how "relationships" should work so I cheated a bit for the state (allowing to provide a code).
I don't like that serializer don't handle deserialisations, had to play camel vs snake case (or I missed something ?).
Found a lib but we still need to verify "ids" are in within the tenant/project so the added values wasn't clear.
In the problem of our "renaming", validation errors still show the original name (eg state vs input) and are not camelized.
=> Wip a first version for create

app/services/descriptor/project_descriptor_factory.rb, spec/fixtures/scorpio/project_descriptor.json, spec/fixtures/scorpio/project_descriptor_for_zone.json
To replicate the same "calculation" for data entries in the js part.
Don't want to rely on the api for data entry so using the descriptor.
=> Expose decision tables for activity package level

app/services/invoicing/invoice_entity.rb, spec/fixtures/dhis2/contracts_events.json, spec/fixtures/dhis2/contracts_program.json, spec/services/invoicing/invoice_entity_spec.rb
main change is here : https://github.com/BLSQ/orbf2/pull/235/files#diff-8e9019ed7752a3410a83e8d2c54834fb40ecad7cb687730af00a82cd021f543fR35
if the orgunits is not contracted it will match "0" packages in the later stages since "groups" are deduced from the program events.
=> Don't check contracted group when program based

lib/parallel_dhis2.rb, spec/lib/parallel_dhis2_spec.rb
I tried to reuse the existing cookiejar we have in our DHIS gem, but
since that stores the cookies in a ruby hash, like so:
{"JSESSIONID"	=> "393D14-and-so-on"}
And typhoeus just passes the file where the cookies are on to Ecto,
which is a wrapper for libcurl, which expect the cookies to be in a
file formatted like this:
#HttpOnly_sandbox.bluesquare.org	FALSE	/	FALSE	0	JSESSIONID	393D14-and-so-on
I tried to fake it by writing the file myself, and giving Typhoeus a
StringIO, but it really needs a file, and since it also has the domain
stuff in it, I figured this might break sooner than that it will help
us.
So, now I just use a tempfile, and the first request of Typhoeus will
fill it, and the others will use it.
So in our DHIS-logs this means one AuthenticationEvent instead of one
per …
=> Use cookies when parallel publishing

app/models/dhis2_snapshot.rb, spec/models/dhis2_snapshot_spec.rb
Sometimes it's handy to find a specific snapshot, or to be able to check if a snapshot has a certain data_element in it.
With these you can now do
Dhis2Snapshot.where(project_anchor_id: 94).data_elements.containing_dhis2_id("abc123")
And it will give you back if it find any matching snapshots of kind 'data_elements' that had a (dhis2) id in it with 'abc123'
=> Scopes to help find snapshots

Dockerfile, Gemfile, Gemfile.lock, app/models/project.rb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, lib/tasks/import_export.rake, lib/tasks/ui.rake
* the docker image is now bundling production asset at build time
* you can specify DISABLE_FORCE_SSL=TRUE (as it's enforced by traefik)
* to support minio there's 
* a minio storage entry where you can specify the S3_SIMULATION_ENDPOINT url of minio api
* RAILS_ACTIVE_STORAGE=minio
* for the "subsetting" of production db : 
* there's a rake task creating a subset db (loosing ids) https://github.com/moiristo/deep_cloneable/issues/136
* for hesabu manager deployment you can specify the ORBF2_URL (but currently the manager is not versionned)
=> Allow some adjustement for local hosting, https, minio for active storage

Dockerfile, script/docker_build
Inspired by this [2 steps build](https://medium.com/@lemuelbarango/ruby-on-rails-smaller-docker-images-bff240931332)
I ended up with this, 1.4GB => 345 MB
```
./script/docker_build
docker images blsq/hesabu
REPOSITORY    TAG                IMAGE ID       CREATED          SIZE
blsq/hesabu   1.0.4.gccbafb8     52b5ce233d6f   4 minutes ago    345MB
blsq/hesabu   0.0.1.5.g8569575   8d608d7e0036   14 minutes ago   393MB
blsq/hesabu   1.0.0.             4f9c4f93293f   4 hours ago      1.4GB
```
to test it I've run the image against staging env with something like this
```
docker run --env-file ../scorpio.env.staging -p 127.0.0.1:3000:3000/tcp blsq/hesabu:1.0.4.gccbafb8
```
when encountering problems run shell script
```
docker run --env-file ../scorpio.env.staging -it blsq/hesabu:1.0.4.gccbafb8 …
```
=> Docker image size reduction

app/controllers/private_controller.rb, spec/controllers/setup/states_controller_spec.rb, spec/rails_helper.rb
feeds whodunnit an id instead of an object, resolving the issue of users not being logged on changes
for reference: https://github.com/paper-trail-gem/paper_trail/search?q=def+user_for_paper_trail
Thanks!
=> fixing whodunnit

app/controllers/api/v2/base_controller.rb, app/controllers/api/v2/children_formulas_controller.rb, app/controllers/api/v2/compound_formulas_controller.rb, app/controllers/api/v2/formulas_controller.rb, app/controllers/api/v2/set_formulas_controller.rb, app/controllers/api/v2/topic_formulas_controller.rb, app/controllers/api/v2/zone_formulas_controller.rb, app/controllers/api/v2/zone_topic_formulas_controller.rb, app/models/formula.rb, app/models/package.rb, app/models/rule.rb, app/models/rule_types/activity_rule_type.rb, app/models/rule_types/base_rule_type.rb, app/models/rule_types/package_rule_type.rb, app/serializers/v2/formula_serializer.rb, config/routes.rb, spec/controllers/api/v2/topic_formulas_controller_spec.rb
This PR adds an update endpoint for formulas, accessible by hesabu-manager. It also adjusts how errors are handled and sent back up to the client so that there is more precise information about validation errors for specific attributes.
=> formula update endpoints, error handling

app/controllers/api/v2/formulas_controller.rb, app/views/setup/changes/index.erb, spec/controllers/api/v2/children_formulas_controller_spec.rb, spec/controllers/api/v2/compound_formulas_controller_spec.rb, spec/controllers/api/v2/set_formulas_controller_spec.rb, spec/controllers/api/v2/topic_formulas_controller_spec.rb, spec/controllers/api/v2/zone_formulas_controller_spec.rb, spec/controllers/api/v2/zone_topic_formulas_controller_spec.rb
the whodunnit wasn't filled, it is now.
=> Force dhis2 user id when showing/creating/deleting
